var = [[{' Regions · Provinces · Cities': '\n', ' ': '\n'},
        {' Regions · Provinces · Cities': '2,781,345\n', ' ': ' 22.7\n', ' Moon Jae-inDemocratic': ' 476,973\n',
         ' Hong Jun-pyoLiberty Korea': ' 7.26\n', " Ahn Cheol-sooPeople's": ' 425,459\n',
         ' Yoo Seung-minBareun': ' 6.47\n'},
        {' Regions · Provinces · Cities': ' 747,090\n', ' ': ' 23.7\n', ' Moon Jae-inDemocratic': ' 118,691\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.54\n', " Ahn Cheol-sooPeople's": ' 129,925\n',
         ' Yoo Seung-minBareun': ' 7.16\n'},
        {' Regions · Provinces · Cities': ' 3,319,812\n', ' ': ' 22.9\n', ' Moon Jae-inDemocratic': ' 540,023\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.84\n', " Ahn Cheol-sooPeople's": ' 546,373\n',
         ' Yoo Seung-minBareun': ' 6.92\n'},
        {' Regions · Provinces · Cities': ' 324,768\n', ' ': ' 21.8\n', ' Moon Jae-inDemocratic': ' 65,278\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.86\n', " Ahn Cheol-sooPeople's": ' 62,389\n',
         ' Yoo Seung-minBareun': ' 6.56\n'},
        {' Regions · Provinces · Cities': ' 404,545\n', ' ': ' 23.2\n', ' Moon Jae-inDemocratic': ' 59,820\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.34\n', " Ahn Cheol-sooPeople's": ' 63,669\n',
         ' Yoo Seung-minBareun': ' 6.75\n'},
        {' Regions · Provinces · Cities': ' 374,806\n', ' ': ' 21.8\n', ' Moon Jae-inDemocratic': ' 57,282\n',
         ' Hong Jun-pyoLiberty Korea': ' 5.90\n', " Ahn Cheol-sooPeople's": ' 65,095\n',
         ' Yoo Seung-minBareun': ' 6.70\n'},
        {' Regions · Provinces · Cities': ' 476,661\n', ' ': ' 23.5\n', ' Moon Jae-inDemocratic': ' 68,521\n',
         ' Hong Jun-pyoLiberty Korea': ' 5.55\n', " Ahn Cheol-sooPeople's": ' 83,868\n',
         ' Yoo Seung-minBareun': ' 6.79\n'},
        {' Regions · Provinces · Cities': ' 77,767\n', ' ': ' 21.0\n', ' Moon Jae-inDemocratic': ' 9,192\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.03\n', " Ahn Cheol-sooPeople's": ' 9,353\n',
         ' Yoo Seung-minBareun': ' 6.14\n'},
        {' Regions · Provinces · Cities': ' 583,847\n', ' ': ' 30.1\n', ' Moon Jae-inDemocratic': ' 20,862\n',
         ' Hong Jun-pyoLiberty Korea': ' 2.18\n', " Ahn Cheol-sooPeople's": ' 43,719\n',
         ' Yoo Seung-minBareun': ' 4.60\n'},
        {' Regions · Provinces · Cities': ' 778,747\n', ' ': ' 23.8\n', ' Moon Jae-inDemocratic': ' 60,802\n',
         ' Hong Jun-pyoLiberty Korea': ' 2.56\n', " Ahn Cheol-sooPeople's": ' 29,296\n',
         ' Yoo Seung-minBareun': ' 4.93\n'},
        {' Regions · Provinces · Cities': ' 737,921\n', ' ': ' 30.7\n', ' Moon Jae-inDemocratic': ' 25,819\n',
         ' Hong Jun-pyoLiberty Korea': ' 2.09\n', " Ahn Cheol-sooPeople's": ' 49,509\n',
         ' Yoo Seung-minBareun': ' 4.01\n'},
        {' Regions · Provinces · Cities': ' 872,127\n', ' ': ' 16.8\n', ' Moon Jae-inDemocratic': ' 162,480\n',
         ' Hong Jun-pyoLiberty Korea': ' 7.21\n', " Ahn Cheol-sooPeople's": ' 94,329\n',
         ' Yoo Seung-minBareun': ' 4.85\n'},
        {' Regions · Provinces · Cities': ' 282,794\n', ' ': ' 17.3\n', ' Moon Jae-inDemocratic': ' 60,289\n',
         ' Hong Jun-pyoLiberty Korea': ' 8.13\n', " Ahn Cheol-sooPeople's": ' 62,187\n',
         ' Yoo Seung-minBareun': ' 8.38\n'},
        {' Regions · Provinces · Cities': ' 342,620\n', ' ': ' 15.0\n', ' Moon Jae-inDemocratic': ' 198,459\n',
         ' Hong Jun-pyoLiberty Korea': ' 12.60\n', " Ahn Cheol-sooPeople's": ' 74,440\n',
         ' Yoo Seung-minBareun': ' 4.72\n'},
        {' Regions · Provinces · Cities': ' 369,726\n', ' ': ' 14.9\n', ' Moon Jae-inDemocratic': ' 149,017\n',
         ' Hong Jun-pyoLiberty Korea': ' 8.75\n', " Ahn Cheol-sooPeople's": ' 88,080\n',
         ' Yoo Seung-minBareun': ' 5.17\n'},
        {' Regions · Provinces · Cities': ' 779,731\n', ' ': ' 13.4\n', ' Moon Jae-inDemocratic': ' 142,479\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.71\n', " Ahn Cheol-sooPeople's": ' 113,051\n',
         ' Yoo Seung-minBareun': ' 5.32\n'},
        {' Regions · Provinces · Cities': ' 169,493\n', ' ': ' 20.9\n', ' Moon Jae-inDemocratic': ' 22,784\n',
         ' Hong Jun-pyoLiberty Korea': ' 6.11\n', " Ahn Cheol-sooPeople's": ' 31,716\n',
         ' Yoo Seung-minBareun': ' 8.51\n'},
        {' Regions · Provinces · Cities': '13,423,800\n', ' ': '21.41%\n', ' Moon Jae-inDemocratic': '  2,208,771\n',
         ' Hong Jun-pyoLiberty Korea': '6.76%\n', " Ahn Cheol-sooPeople's": '  2,017,458\n',
         ' Yoo Seung-minBareun': '6.17%\n'}], [], [],
       [{' Moon Jae-in': '\nDemocratic Party candidate\n'}, {' Moon Jae-in': ' \n'},
        {' Moon Jae-in': ' Chairman of theDemocratic Party of Korea(2015–2016)\n'}], [
           {' Polling firm/Link': '\n', ' Fieldwork date': '\n', ' Samplesize': '\n', ' Lee Jae-myung': '\n',
            ' Moon Jae-in': '\n', ' Ahn Hee-jung': '\n', ' Kim Boo-kyum': '\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.03.10\n', ' Samplesize': ' 374\n',
            ' Lee Jae-myung': ' 21.9%\n', ' Moon Jae-in': '52.7%\n', ' Ahn Hee-jung': ' 22.5%\n',
            ' Kim Boo-kyum': ' –\n', ' Park Won-soon': ' –\n', ' Kim Jong-in': ' –\n', ' Choi Sung': ' 0.4%\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.02.27–17.02.28\n', ' Samplesize': ' 1,111\n',
            ' Lee Jae-myung': ' 15.5%\n', ' Moon Jae-in': '38.0%\n', ' Ahn Hee-jung': ' 29.8%\n',
            ' Kim Boo-kyum': ' –\n', ' Park Won-soon': ' –\n', ' Kim Jong-in': ' –\n', ' Choi Sung': ' 0.2%\n'},
           {' Polling firm/Link': ' Korea Research\n', ' Fieldwork date': ' 17.02.05–17.02.06\n',
            ' Samplesize': ' 2,016\n', ' Lee Jae-myung': ' 8.8%\n', ' Moon Jae-in': '36.9%\n',
            ' Ahn Hee-jung': ' 26.2%\n', ' Kim Boo-kyum': ' 2.4%\n', ' Park Won-soon': ' –\n', ' Kim Jong-in': ' –\n',
            ' Choi Sung': ' –\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.02.01\n', ' Samplesize': ' 528\n',
            ' Lee Jae-myung': ' 13.9%\n', ' Moon Jae-in': '31.4%\n', ' Ahn Hee-jung': ' 23.7%\n',
            ' Kim Boo-kyum': ' 4.1%\n', ' Park Won-soon': ' –\n', ' Kim Jong-in': ' 3.7%\n', ' Choi Sung': ' 0.5%\n'},
           {' Polling firm/Link': 'Realmeter\n', ' Fieldwork date': ' 17.01.16–17.01.17\n', ' Samplesize': ' 1,004\n',
            ' Lee Jae-myung': ' 13.5%\n', ' Moon Jae-in': '32.8%\n', ' Ahn Hee-jung': ' 10.8%\n',
            ' Kim Boo-kyum': ' 5.6%\n', ' Park Won-soon': ' 5.3%\n', ' Kim Jong-in': ' 5%\n', ' Choi Sung': ' 1.1%\n'}],
       [], [{' Hong Jun-pyo': '\nLiberty Korea Party candidate\n'}, {' Hong Jun-pyo': ' \n'},
            {' Hong Jun-pyo': ' Governor ofSouth Gyeongsang Province(2012–2017)\n'}], [],
       [{' Ahn Cheol-soo': "\nPeople's Party candidate\n"}, {' Ahn Cheol-soo': ' \n'},
        {' Ahn Cheol-soo': " Chairman of thePeople's Party(2016)\n"}], [],
       [{' Yoo Seong-min': '\nBareun Party candidate\n'}, {' Yoo Seong-min': ' \n'},
        {' Yoo Seong-min': ' Member of theNational Assembly(2005– )\n'}], [],
       [{' Sim Sang-jung': '\nJustice Party candidate\n'}, {' Sim Sang-jung': ' \n'},
        {' Sim Sang-jung': ' Chairwoman of theJustice Party(2015– )\n'}], [], [
           {'South Korean Presidential Election, 2017': '14 April10:00 KST\n',
            'Date': 'SBSJournalists Association of Korea\n', 'Organizers': 'Kim Sung-joon\n', 'Moderators': 'P\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': 'P\n',
            'Notes': 'P\n', 'Sim Sang-jung': 'P\n', 'Moon Jae-in': 'P\n', 'Ahn Cheol-soo': '[33][34][35][36]\n'},
           {'South Korean Presidential Election, 2017': '19 April22:00 KST\n', 'Date': 'KBS\n',
            'Organizers': 'Park Young-hwan\n', 'Moderators': 'P\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': 'P\n',
            'Notes': 'P\n', 'Sim Sang-jung': 'P\n', 'Moon Jae-in': 'P\n', 'Ahn Cheol-soo': '[36]\n'},
           {'South Korean Presidential Election, 2017': '23 April20:00 KST\n', 'Date': 'NEC\n',
            'Organizers': 'Kim Jin-suk\n', 'Moderators': 'P\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': 'P\n',
            'Notes': 'P\n', 'Sim Sang-jung': 'P\n', 'Moon Jae-in': 'P\n', 'Ahn Cheol-soo': '[36]\n'},
           {'South Korean Presidential Election, 2017': '25 April21:00 KST\n',
            'Date': 'JTBCThe Korean Political Science Association\n', 'Organizers': 'Sohn Suk-hee\n',
            'Moderators': 'P\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': 'P\n',
            'Notes': 'P\n', 'Sim Sang-jung': 'P\n', 'Moon Jae-in': 'P\n', 'Ahn Cheol-soo': '[36]\n'},
           {'South Korean Presidential Election, 2017': '28 April20:00 KST\n', 'Date': 'NEC\n',
            'Organizers': 'Park Yong-chan\n', 'Moderators': 'P\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': 'P\n',
            'Notes': 'P\n', 'Sim Sang-jung': 'P\n', 'Moon Jae-in': 'P\n', 'Ahn Cheol-soo': '[36]\n'},
           {'South Korean Presidential Election, 2017': '2nd May20:00 KST\n', 'Date': 'NEC\n',
            'Organizers': 'Lee Jung-hee\n', 'Moderators': 'P\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': 'P\n',
            'Notes': 'P\n', 'Sim Sang-jung': 'P\n', 'Moon Jae-in': 'P\n', 'Ahn Cheol-soo': '[36]\n'},
           {'South Korean Presidential Election, 2017': '\n', 'Date': '\n', 'Organizers': '\n', 'Moderators': '\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': '\n'},
           {'South Korean Presidential Election, 2017': ' Realmeter\n', 'Date': ' 12.2%\n', 'Organizers': ' 33.7%\n',
            'Moderators': ' 21.7%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 11.8%\n',
            'Notes': ' 9.6%\n', 'Sim Sang-jung': ' [37]\n'},
           {'South Korean Presidential Election, 2017': ' JoonAng Ilbo\n', 'Date': ' 13.1%\n', 'Organizers': ' 22.3%\n',
            'Moderators': ' 16.5%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 25.0%\n',
            'Notes': ' 5.4%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Hankook Research\n', 'Date': ' 15.1%\n',
            'Organizers': ' 21.2%\n', 'Moderators': ' 16.2%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 28.1%\n',
            'Notes': ' 7.5%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' KSOI\n', 'Date': ' 21.9%\n', 'Organizers': ' 15.0%\n',
            'Moderators': ' 11.1%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 21.5%\n',
            'Notes': ' 6.5%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' JoonAng Ilbo\n', 'Date': ' 22.0%\n', 'Organizers': ' 17.4%\n',
            'Moderators': ' 9.0%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 23.7%\n',
            'Notes': ' 6.7%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Hankook Research\n', 'Date': ' 27.2%\n',
            'Organizers': ' 12.6%\n', 'Moderators': ' 5.1%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 22.1%\n',
            'Notes': ' 5.9%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Hankook Research\n', 'Date': ' 40.6%\n',
            'Organizers': ' 13.2%\n', 'Moderators': ' 6.1%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 14.4%\n',
            'Notes': ' 9.9%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Gallup Korea\n', 'Date': ' 30%\n', 'Organizers': ' 18%\n',
            'Moderators': ' 6%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 14%\n',
            'Notes': ' 9%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' The Opinion\n', 'Date': ' 35.8%\n', 'Organizers': ' 13.5%\n',
            'Moderators': ' 5.9%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 14.6%\n',
            'Notes': ' 11.5%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' JoongAng Ilbo\n', 'Date': ' 38.1%\n',
            'Organizers': ' 11.5%\n', 'Moderators': ' 4.5%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 16.6%\n',
            'Notes': ' 10.0%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Gallup Korea\n', 'Date': ' 34.8%\n', 'Organizers': ' 14.4%\n',
            'Moderators': ' 4.4%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 12.7%\n',
            'Notes': ' 13.3%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Research & Research\n', 'Date': ' 41.8%\n',
            'Organizers': ' 9.3%\n', 'Moderators': ' 4.0%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 18.4%\n',
            'Notes': ' 9.9%\n', 'Sim Sang-jung': '\n'},
           {'South Korean Presidential Election, 2017': ' Kantar\n', 'Date': ' 40.4%\n', 'Organizers': ' 11.8%\n',
            'Moderators': ' 3.9%\n',
            '\xa0P\xa0 Present \xa0I\xa0 Invitee \xa0NI\xa0 Non-invitee \xa0A\xa0 Absent invitee': ' 19.2%\n',
            'Notes': ' 11.0%\n', 'Sim Sang-jung': '\n'}], [
           {' Polling firm/Link': '\n', ' Fieldwork date': '\n', ' Samplesize': '\n', ' Sim Sang-jung': '\n',
            ' Moon Jae-in': '\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.05.09\n', ' Samplesize': 'Election Day\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.05.04- 17.05.05\n', ' Samplesize': 'Early Voting\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.05.03- 17.05.09\n',
            ' Samplesize': 'Poll Blackout period\n'},
           {' Polling firm/Link': 'Embrain\n', ' Fieldwork date': ' 17.05.02\n', ' Samplesize': ' 2,058\n',
            ' Sim Sang-jung': ' 7.2%\n', ' Moon Jae-in': ' 40.6%\n', ' Ahn Cheol-soo': ' 17.8%\n',
            ' Yoo Seong-min': ' 4.2%\n', ' Hong Jun-pyo': ' 19.6%\n'},
           {' Polling firm/Link': 'Research Plus\n', ' Fieldwork date': ' 17.05.01–17.05.02\n',
            ' Samplesize': ' 1,011\n', ' Sim Sang-jung': ' 5.6%\n', ' Moon Jae-in': ' 39.7%\n',
            ' Ahn Cheol-soo': ' 18.9%\n', ' Yoo Seong-min': ' 4.6%\n', ' Hong Jun-pyo': ' 13.7%\n'},
           {' Polling firm/Link': 'Kantar\n', ' Fieldwork date': ' 17.05.01–17.05.02\n', ' Samplesize': ' 1,147\n',
            ' Sim Sang-jung': ' 6.8%\n', ' Moon Jae-in': ' 38.5%\n', ' Ahn Cheol-soo': ' 15.7%\n',
            ' Yoo Seong-min': ' 3.8%\n', ' Hong Jun-pyo': ' 16.8%\n'},
           {' Polling firm/Link': 'Hankook Research\n', ' Fieldwork date': ' 17.05.01–17.05.02\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 11.2%\n', ' Moon Jae-in': ' 38.0%\n',
            ' Ahn Cheol-soo': ' 21.0%\n', ' Yoo Seong-min': ' 4.0%\n', ' Hong Jun-pyo': ' 16.8%\n'},
           {' Polling firm/Link': 'JoWon C&I\n', ' Fieldwork date': ' 17.05.01–17.05.02\n', ' Samplesize': ' 1,035\n',
            ' Sim Sang-jung': ' 8.7%\n', ' Moon Jae-in': ' 36.1%\n', ' Ahn Cheol-soo': ' 22.3%\n',
            ' Yoo Seong-min': ' 3.6%\n', ' Hong Jun-pyo': ' 16.9%\n'},
           {' Polling firm/Link': 'Research & Research\n', ' Fieldwork date': ' 17.05.01–17.05.02\n',
            ' Samplesize': ' 1,058\n', ' Sim Sang-jung': ' 8.1%\n', ' Moon Jae-in': ' 40.2%\n',
            ' Ahn Cheol-soo': ' 19.9%\n', ' Yoo Seong-min': ' 5.7%\n', ' Hong Jun-pyo': ' 17.7%\n'},
           {' Polling firm/Link': 'Gallup Korea\n', ' Fieldwork date': ' 17.05.01–17.05.02\n',
            ' Samplesize': ' 1,015\n', ' Sim Sang-jung': ' 8%\n', ' Moon Jae-in': ' 38%\n', ' Ahn Cheol-soo': ' 20%\n',
            ' Yoo Seong-min': ' 6%\n', ' Hong Jun-pyo': ' 16%\n'},
           {' Polling firm/Link': 'Yeouido\n', ' Fieldwork date': ' 17.05.01–17.05.02\n', ' Samplesize': ' 2,182\n',
            ' Sim Sang-jung': ' 6.4%\n', ' Moon Jae-in': ' 39.4%\n', ' Ahn Cheol-soo': ' 20.1%\n',
            ' Yoo Seong-min': ' 4.5%\n', ' Hong Jun-pyo': ' 24.9%\n'},
           {' Polling firm/Link': 'Realmeter\n', ' Fieldwork date': ' 17.05.01–17.05.02\n', ' Samplesize': ' 1,016\n',
            ' Sim Sang-jung': ' 7.3%\n', ' Moon Jae-in': ' 42.4%\n', ' Ahn Cheol-soo': ' 18.6%\n',
            ' Yoo Seong-min': ' 4.9%\n', ' Hong Jun-pyo': ' 18.6%\n'},
           {' Polling firm/Link': 'Hankook Research\n', ' Fieldwork date': ' 17.05.01–17.05.02\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 8.4%\n', ' Moon Jae-in': ' 40.2%\n',
            ' Ahn Cheol-soo': ' 19.7%\n', ' Yoo Seong-min': ' 5.1%\n', ' Hong Jun-pyo': ' 16.2%\n'},
           {' Polling firm/Link': 'ResearchView\n', ' Fieldwork date': ' 17.04.30–17.05.02\n',
            ' Samplesize': ' 2,053\n', ' Sim Sang-jung': ' 8.0%\n', ' Moon Jae-in': ' 43.2%\n',
            ' Ahn Cheol-soo': ' 21.1%\n', ' Yoo Seong-min': ' 4.8%\n', ' Hong Jun-pyo': ' 20.1%\n'},
           {' Polling firm/Link': 'MetriX\n', ' Fieldwork date': ' 17.04.30–17.05.02\n', ' Samplesize': ' 1,500\n',
            ' Sim Sang-jung': ' 9.1%\n', ' Moon Jae-in': ' 39.2%\n', ' Ahn Cheol-soo': ' 21.5%\n',
            ' Yoo Seong-min': ' 4.3%\n', ' Hong Jun-pyo': ' 16.7%\n'},
           {' Polling firm/Link': 'Embrain\n', ' Fieldwork date': ' 17.05.01\n', ' Samplesize': ' 1,018\n',
            ' Sim Sang-jung': ' 9.0%\n', ' Moon Jae-in': ' 38.6%\n', ' Ahn Cheol-soo': ' 22.6%\n',
            ' Yoo Seong-min': ' 3.7%\n', ' Hong Jun-pyo': ' 18.3%\n'},
           {' Polling firm/Link': 'JoWon C&I\n', ' Fieldwork date': ' 17.04.30–17.05.01\n', ' Samplesize': ' 1,046\n',
            ' Sim Sang-jung': ' 8.7%\n', ' Moon Jae-in': ' 39.5%\n', ' Ahn Cheol-soo': ' 23.9%\n',
            ' Yoo Seong-min': ' 3.5%\n', ' Hong Jun-pyo': ' 18.4%\n'},
           {' Polling firm/Link': 'R&Search\n', ' Fieldwork date': ' 17.04.30–17.05.01\n', ' Samplesize': ' 1,961\n',
            ' Sim Sang-jung': ' 8.7%\n', ' Moon Jae-in': ' 41.8%\n', ' Ahn Cheol-soo': ' 19.4%\n',
            ' Yoo Seong-min': ' 3.9%\n', ' Hong Jun-pyo': ' 21.2%\n'},
           {' Polling firm/Link': 'Research & Research\n', ' Fieldwork date': ' 17.04.30–17.05.01\n',
            ' Samplesize': ' 1,027\n', ' Sim Sang-jung': ' 9.8%\n', ' Moon Jae-in': ' 39.7%\n',
            ' Ahn Cheol-soo': ' 20.2%\n', ' Yoo Seong-min': ' 5.1%\n', ' Hong Jun-pyo': ' 16.4%\n'},
           {' Polling firm/Link': 'JoongAng Ilbo\n', ' Fieldwork date': ' 17.04.30–17.05.01\n',
            ' Samplesize': ' 2,000\n', ' Sim Sang-jung': ' 9.2%\n', ' Moon Jae-in': ' 39.3%\n',
            ' Ahn Cheol-soo': ' 21.8%\n', ' Yoo Seong-min': ' 4.9%\n', ' Hong Jun-pyo': ' 16.5%\n'},
           {' Polling firm/Link': 'Gallup Korea\n', ' Fieldwork date': ' 17.04.30–17.05.01\n',
            ' Samplesize': ' 3,077\n', ' Sim Sang-jung': ' 8.4%\n', ' Moon Jae-in': ' 37.7%\n',
            ' Ahn Cheol-soo': ' 19.1%\n', ' Yoo Seong-min': ' 3.6%\n', ' Hong Jun-pyo': ' 14.9%\n'}], [
           {' Polling firm/Link': '\n', ' Fieldwork date': '\n', ' Samplesize': '\n', ' Sim Sang-jung': '\n',
            ' Moon Jae-in': '\n'},
           {' Polling firm/Link': 'Research & Research\n', ' Fieldwork date': ' 17.04.29–17.04.30\n',
            ' Samplesize': ' 1,004\n', ' Sim Sang-jung': ' 8.1%\n', ' Moon Jae-in': ' 39.4%\n',
            ' Ahn Cheol-soo': ' 20.8%\n', ' Yoo Seong-min': ' 4.8%\n', ' Hong Jun-pyo': ' 16.2%\n'},
           {' Polling firm/Link': 'Hankook Research\n', ' Fieldwork date': ' 17.04.29–17.04.30\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 11.4%\n', ' Moon Jae-in': ' 38.7%\n',
            ' Ahn Cheol-soo': ' 23.4%\n', ' Yoo Seong-min': ' 5.7%\n', ' Hong Jun-pyo': ' 14.4%\n'},
           {' Polling firm/Link': 'The Opinion\n', ' Fieldwork date': ' 17.04.29–17.04.30\n', ' Samplesize': ' 1,000\n',
            ' Sim Sang-jung': ' 6.9%\n', ' Moon Jae-in': ' 37.3%\n', ' Ahn Cheol-soo': ' 20.5%\n',
            ' Yoo Seong-min': ' 4.9%\n', ' Hong Jun-pyo': ' 15.8%\n'},
           {' Polling firm/Link': 'STI\n', ' Fieldwork date': ' 17.04.29–17.04.30\n', ' Samplesize': ' 1,000\n',
            ' Sim Sang-jung': ' 8.2%\n', ' Moon Jae-in': ' 46.0%\n', ' Ahn Cheol-soo': ' 19.2%\n',
            ' Yoo Seong-min': ' 4.8%\n', ' Hong Jun-pyo': ' 17.4%\n'},
           {' Polling firm/Link': 'Ace Research\n', ' Fieldwork date': ' 17.04.29\n', ' Samplesize': ' 1,023\n',
            ' Sim Sang-jung': ' 7.6%\n', ' Moon Jae-in': ' 41.1%\n', ' Ahn Cheol-soo': ' 21.5%\n',
            ' Yoo Seong-min': ' 4.3%\n', ' Hong Jun-pyo': ' 20.8%\n'},
           {' Polling firm/Link': 'MetriX\n', ' Fieldwork date': ' 17.04.28–17.04.29\n', ' Samplesize': ' 1,000\n',
            ' Sim Sang-jung': ' 7.2%\n', ' Moon Jae-in': ' 39.8%\n', ' Ahn Cheol-soo': ' 21.0%\n',
            ' Yoo Seong-min': ' 4.1%\n', ' Hong Jun-pyo': ' 15.4%\n'},
           {' Polling firm/Link': 'KSOI\n', ' Fieldwork date': ' 17.04.28–17.04.29\n', ' Samplesize': ' 1,000\n',
            ' Sim Sang-jung': ' 8.6%\n', ' Moon Jae-in': ' 41.4%\n', ' Ahn Cheol-soo': ' 22.1%\n',
            ' Yoo Seong-min': ' 6.3%\n', ' Hong Jun-pyo': ' 16.6%\n'},
           {' Polling firm/Link': 'Realmeter\n', ' Fieldwork date': ' 17.04.27–17.04.29\n', ' Samplesize': ' 1,523\n',
            ' Sim Sang-jung': ' 7.6%\n', ' Moon Jae-in': ' 42.6%\n', ' Ahn Cheol-soo': ' 20.9%\n',
            ' Yoo Seong-min': ' 5.2%\n', ' Hong Jun-pyo': ' 16.7%\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.04.28\n',
            ' Samplesize': 'Fifth presidential debate held by NEC\n'},
           {' Polling firm/Link': 'Gallup Korea\n', ' Fieldwork date': ' 17.04.25–17.04.27\n',
            ' Samplesize': ' 1,006\n', ' Sim Sang-jung': ' 7%\n', ' Moon Jae-in': ' 40%\n', ' Ahn Cheol-soo': ' 24%\n',
            ' Yoo Seong-min': ' 4%\n', ' Hong Jun-pyo': ' 12%\n'},
           {' Polling firm/Link': 'ResearchView\n', ' Fieldwork date': ' 17.04.25–17.04.27\n',
            ' Samplesize': ' 1,418\n', ' Sim Sang-jung': ' 6.8%\n', ' Moon Jae-in': ' 45.5%\n',
            ' Ahn Cheol-soo': ' 23.7%\n', ' Yoo Seong-min': ' 3.9%\n', ' Hong Jun-pyo': ' 15.3%\n'},
           {' Polling firm/Link': 'Hankook Research\n', ' Fieldwork date': ' 17.04.25–17.04.26\n',
            ' Samplesize': ' 2,000\n', ' Sim Sang-jung': ' 7.5%\n', ' Moon Jae-in': ' 38.5%\n',
            ' Ahn Cheol-soo': ' 25.2%\n', ' Yoo Seong-min': ' 4.9%\n', ' Hong Jun-pyo': ' 12.3%\n'},
           {' Polling firm/Link': 'Realmeter\n', ' Fieldwork date': ' 17.04.24–17.04.26\n', ' Samplesize': ' 1,520\n',
            ' Sim Sang-jung': ' 7.5%\n', ' Moon Jae-in': ' 44.4%\n', ' Ahn Cheol-soo': ' 22.8%\n',
            ' Yoo Seong-min': ' 5.4%\n', ' Hong Jun-pyo': ' 13.0%\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.04.25\n',
            ' Samplesize': 'Fourth presidential debate held by JTBC\n'},
           {' Polling firm/Link': 'Hankook Research\n', ' Fieldwork date': ' 17.04.24–17.04.25\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 8.0%\n', ' Moon Jae-in': ' 40.4%\n',
            ' Ahn Cheol-soo': ' 26.4%\n', ' Yoo Seong-min': ' 5.1%\n', ' Hong Jun-pyo': ' 10.8%\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.04.23–17.04.25\n', ' Samplesize': ' 1,772\n',
            ' Sim Sang-jung': ' 4.3%\n', ' Moon Jae-in': ' 44.3%\n', ' Ahn Cheol-soo': ' 26.1%\n',
            ' Yoo Seong-min': ' 4.6%\n', ' Hong Jun-pyo': ' 14.8%\n'},
           {' Polling firm/Link': ' MetriX\n', ' Fieldwork date': ' 17.04.23–17.04.24\n', ' Samplesize': ' 1,500\n',
            ' Sim Sang-jung': ' 4.7%\n', ' Moon Jae-in': ' 40.3%\n', ' Ahn Cheol-soo': ' 29.6%\n',
            ' Yoo Seong-min': ' 3.4%\n', ' Hong Jun-pyo': ' 9.7%\n'},
           {' Polling firm/Link': ' JoongAng Ilbo\n', ' Fieldwork date': ' 17.04.23–17.04.24\n',
            ' Samplesize': ' 2,000\n', ' Sim Sang-jung': ' 5.0%\n', ' Moon Jae-in': ' 39.8%\n',
            ' Ahn Cheol-soo': ' 29.4%\n', ' Yoo Seong-min': ' 4.4%\n', ' Hong Jun-pyo': ' 11.7%\n'},
           {' Polling firm/Link': ' JoWon C&I\n', ' Fieldwork date': ' 17.04.22–17.04.24\n', ' Samplesize': ' 1,010\n',
            ' Sim Sang-jung': ' 3.8%\n', ' Moon Jae-in': ' 39.4%\n', ' Ahn Cheol-soo': ' 31.1%\n',
            ' Yoo Seong-min': ' 4.2%\n', ' Hong Jun-pyo': ' 13.9%\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.04.23\n',
            ' Samplesize': 'Third presidential debate held by NEC\n'},
           {' Polling firm/Link': ' Kantar\n', ' Fieldwork date': ' 17.04.21–17.04.22\n', ' Samplesize': ' 1,030\n',
            ' Sim Sang-jung': ' 3.3%\n', ' Moon Jae-in': ' 37.5%\n', ' Ahn Cheol-soo': ' 26.4%\n',
            ' Yoo Seong-min': ' 2.9%\n', ' Hong Jun-pyo': ' 7.6%\n'},
           {' Polling firm/Link': ' KSOI\n', ' Fieldwork date': ' 17.04.21–17.04.22\n', ' Samplesize': ' 1,021\n',
            ' Sim Sang-jung': ' 5.1%\n', ' Moon Jae-in': ' 42.5%\n', ' Ahn Cheol-soo': ' 30.4%\n',
            ' Yoo Seong-min': ' 5.7%\n', ' Hong Jun-pyo': ' 8.9%\n'},
           {' Polling firm/Link': ' Research & Research\n', ' Fieldwork date': ' 17.04.21–17.04.22\n',
            ' Samplesize': ' 1,514\n', ' Sim Sang-jung': ' 4.1%\n', ' Moon Jae-in': ' 39.1%\n',
            ' Ahn Cheol-soo': ' 30.1%\n', ' Yoo Seong-min': ' 3.8%\n', ' Hong Jun-pyo': ' 9.5%\n'},
           {' Polling firm/Link': ' ResearchView\n', ' Fieldwork date': ' 17.04.18–17.04.20\n',
            ' Samplesize': ' 2,004\n', ' Sim Sang-jung': ' 5.0%\n', ' Moon Jae-in': ' 43.3%\n',
            ' Ahn Cheol-soo': ' 31.3%\n', ' Yoo Seong-min': ' 3.8%\n', ' Hong Jun-pyo': ' 11.4%\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.04.18–17.04.20\n',
            ' Samplesize': ' 1,004\n', ' Sim Sang-jung': ' 4%\n', ' Moon Jae-in': ' 41%\n', ' Ahn Cheol-soo': ' 30%\n',
            ' Yoo Seong-min': ' 3%\n', ' Hong Jun-pyo': ' 9%\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.04.19\n',
            ' Samplesize': 'Second presidential debate held on KBS\n'},
           {' Polling firm/Link': ' Research & Research\n', ' Fieldwork date': ' 17.04.18–17.04.19\n',
            ' Samplesize': ' 1,009\n', ' Sim Sang-jung': ' 4.7%\n', ' Moon Jae-in': ' 40.0%\n',
            ' Ahn Cheol-soo': ' 30.1%\n', ' Yoo Seong-min': ' 2.5%\n', ' Hong Jun-pyo': ' 10.2%\n'},
           {' Polling firm/Link': ' EMBRAIN\n', ' Fieldwork date': ' 17.04.18–17.04.19\n', ' Samplesize': ' 1,054\n',
            ' Sim Sang-jung': ' 2.8%\n', ' Moon Jae-in': ' 40.9%\n', ' Ahn Cheol-soo': ' 34.4%\n',
            ' Yoo Seong-min': ' 2.7%\n', ' Hong Jun-pyo': ' 9.5%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.04.18–17.04.19\n',
            ' Samplesize': ' 1,200\n', ' Sim Sang-jung': ' 3.6%\n', ' Moon Jae-in': ' 42.0%\n',
            ' Ahn Cheol-soo': ' 31.8%\n', ' Yoo Seong-min': ' 3.9%\n', ' Hong Jun-pyo': ' 8.5%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.04.17–17.04.18\n', ' Samplesize': ' 1,012\n',
            ' Sim Sang-jung': ' 4.2%\n', ' Moon Jae-in': ' 43.8%\n', ' Ahn Cheol-soo': ' 32.3%\n',
            ' Yoo Seong-min': ' 3.2%\n', ' Hong Jun-pyo': ' 10.2%\n'},
           {' Polling firm/Link': ' EMBRAIN\n', ' Fieldwork date': ' 17.04.17\n', ' Samplesize': ' 1,049\n',
            ' Sim Sang-jung': ' 3.5%\n', ' Moon Jae-in': ' 37.7%\n', ' Ahn Cheol-soo': ' 34.6%\n',
            ' Yoo Seong-min': ' 3.4%\n', ' Hong Jun-pyo': ' 8.5%\n'},
           {' Polling firm/Link': ' JoWon C&I\n', ' Fieldwork date': ' 17.04.15–17.04.16\n', ' Samplesize': ' 1,063\n',
            ' Sim Sang-jung': ' 3.2%\n', ' Moon Jae-in': ' 39.7%\n', ' Ahn Cheol-soo': ' 32.8%\n',
            ' Yoo Seong-min': ' 4.7%\n', ' Hong Jun-pyo': ' 13.1%\n'},
           {' Polling firm/Link': ' JoongAng Ilbo\n', ' Fieldwork date': ' 17.04.15–17.04.16\n',
            ' Samplesize': ' 2,000\n', ' Sim Sang-jung': ' 3.7%\n', ' Moon Jae-in': ' 38.5%\n',
            ' Ahn Cheol-soo': ' 37.3%\n', ' Yoo Seong-min': ' 3.9%\n', ' Hong Jun-pyo': ' 7.4%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.04.15–17.04.16\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 3.9%\n', ' Moon Jae-in': ' 42.6%\n',
            ' Ahn Cheol-soo': ' 35.6%\n', ' Yoo Seong-min': ' 2.7%\n', ' Hong Jun-pyo': ' 7.3%\n'},
           {' Polling firm/Link': ' Kantar\n', ' Fieldwork date': ' 17.04.14–17.04.15\n', ' Samplesize': ' 1,039\n',
            ' Sim Sang-jung': ' 2.8%\n', ' Moon Jae-in': ' 35.8%\n', ' Ahn Cheol-soo': ' 30.2%\n',
            ' Yoo Seong-min': ' 2.8%\n', ' Hong Jun-pyo': ' 8.4%\n'},
           {' Polling firm/Link': ' KSOI\n', ' Fieldwork date': ' 17.04.14–17.04.15\n', ' Samplesize': ' 1,015\n',
            ' Sim Sang-jung': ' 2.9%\n', ' Moon Jae-in': ' 46.9%\n', ' Ahn Cheol-soo': ' 34.4%\n',
            ' Yoo Seong-min': ' 3.4%\n', ' Hong Jun-pyo': ' 6.8%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.04.14\n', ' Samplesize': ' 1,011\n',
            ' Sim Sang-jung': ' 4.5%\n', ' Moon Jae-in': ' 45.4%\n', ' Ahn Cheol-soo': ' 30.7%\n',
            ' Yoo Seong-min': ' 3.8%\n', ' Hong Jun-pyo': ' 8.9%\n'},
           {' Polling firm/Link': '\n', ' Fieldwork date': '17.04.13\n',
            ' Samplesize': 'First presidential debate held on SBS\n'},
           {' Polling firm/Link': ' ResearchView\n', ' Fieldwork date': ' 17.04.12–17.04.13\n',
            ' Samplesize': ' 1,253\n', ' Sim Sang-jung': ' 3.0%\n', ' Moon Jae-in': ' 46.0%\n',
            ' Ahn Cheol-soo': ' 36.5%\n', ' Yoo Seong-min': ' 2.4%\n', ' Hong Jun-pyo': ' 8.8%\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.04.11–17.04.13\n',
            ' Samplesize': ' 1,010\n', ' Sim Sang-jung': ' 3%\n', ' Moon Jae-in': ' 40%\n', ' Ahn Cheol-soo': ' 37%\n',
            ' Yoo Seong-min': ' 3%\n', ' Hong Jun-pyo': ' 7%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.04.11–17.04.12\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 2.7%\n', ' Moon Jae-in': ' 38.0%\n',
            ' Ahn Cheol-soo': ' 38.3%\n', ' Yoo Seong-min': ' 2.1%\n', ' Hong Jun-pyo': ' 6.5%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.04.10–17.04.12\n', ' Samplesize': ' 1,525\n',
            ' Sim Sang-jung': ' 2.8%\n', ' Moon Jae-in': ' 44.8%\n', ' Ahn Cheol-soo': ' 36.5%\n',
            ' Yoo Seong-min': ' 1.7%\n', ' Hong Jun-pyo': ' 8.1%\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.04.09–17.04.11\n', ' Samplesize': ' 1,997\n',
            ' Sim Sang-jung': ' 3.6%\n', ' Moon Jae-in': ' 42.3%\n', ' Ahn Cheol-soo': ' 37.0%\n',
            ' Yoo Seong-min': ' 2.0%\n', ' Hong Jun-pyo': ' 9.1%\n'},
           {' Polling firm/Link': ' JoWon C&I\n', ' Fieldwork date': ' 17.04.08–17.04.10\n', ' Samplesize': ' 1,046\n',
            ' Sim Sang-jung': ' 3.5%\n', ' Moon Jae-in': ' 40.6%\n', ' Ahn Cheol-soo': ' 34.4%\n',
            ' Yoo Seong-min': ' 2.9%\n', ' Hong Jun-pyo': ' 8.7%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.04.08–17.04.09\n', ' Samplesize': ' 1,018\n',
            ' Sim Sang-jung': ' 4.2%\n', ' Moon Jae-in': ' 41.1%\n', ' Ahn Cheol-soo': ' 34.8%\n',
            ' Yoo Seong-min': ' 2.2%\n', ' Hong Jun-pyo': ' 8.6%\n'},
           {' Polling firm/Link': ' Korea Research Center\n', ' Fieldwork date': ' 17.04.08–17.04.09\n',
            ' Samplesize': ' 2,011\n', ' Sim Sang-jung': ' 2.8%\n', ' Moon Jae-in': ' 32.7%\n',
            ' Ahn Cheol-soo': ' 36.8%\n', ' Yoo Seong-min': ' 1.5%\n', ' Hong Jun-pyo': ' 6.5%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.04.07–17.04.08\n', ' Samplesize': ' 2,244\n',
            ' Sim Sang-jung': ' 3.3%\n', ' Moon Jae-in': ' 42.6%\n', ' Ahn Cheol-soo': ' 37.2%\n',
            ' Yoo Seong-min': ' 2.4%\n', ' Hong Jun-pyo': ' 8.4%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.04.07–17.04.08\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 3.6%\n', ' Moon Jae-in': ' 37.7%\n',
            ' Ahn Cheol-soo': ' 37.0%\n', ' Yoo Seong-min': ' 3.0%\n', ' Hong Jun-pyo': ' 6.7%\n'},
           {' Polling firm/Link': ' Research & Research\n', ' Fieldwork date': ' 17.04.07–17.04.08\n',
            ' Samplesize': ' 1,500\n', ' Sim Sang-jung': ' 3.2%\n', ' Moon Jae-in': ' 35.2%\n',
            ' Ahn Cheol-soo': ' 34.5%\n', ' Yoo Seong-min': ' 2.8%\n', ' Hong Jun-pyo': ' 7.4%\n'},
           {' Polling firm/Link': ' KSOI\n', ' Fieldwork date': ' 17.04.07–17.04.08\n', ' Samplesize': ' 1,007\n',
            ' Sim Sang-jung': ' 2.9%\n', ' Moon Jae-in': ' 39.6%\n', ' Ahn Cheol-soo': ' 35.6%\n',
            ' Yoo Seong-min': ' 2.7%\n', ' Hong Jun-pyo': ' 5.8%\n'},
           {' Polling firm/Link': ' Kantar\n', ' Fieldwork date': ' 17.04.07–17.04.08\n', ' Samplesize': ' 2,300\n',
            ' Sim Sang-jung': ' 2.3%\n', ' Moon Jae-in': ' 32.2%\n', ' Ahn Cheol-soo': ' 34.4%\n',
            ' Yoo Seong-min': ' 1.9%\n', ' Hong Jun-pyo': ' 5.7%\n'},
           {' Polling firm/Link': ' Research Plus\n', ' Fieldwork date': ' 17.04.07–17.04.08\n',
            ' Samplesize': ' 1,023\n', ' Sim Sang-jung': ' 2.0%\n', ' Moon Jae-in': ' 37.7%\n',
            ' Ahn Cheol-soo': ' 37.7%\n', ' Yoo Seong-min': ' 2.1%\n', ' Hong Jun-pyo': ' 6.6%\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.04.04–17.04.06\n',
            ' Samplesize': ' 1,005\n', ' Sim Sang-jung': ' 3%\n', ' Moon Jae-in': ' 38%\n', ' Ahn Cheol-soo': ' 35%\n',
            ' Yoo Seong-min': ' 4%\n', ' Hong Jun-pyo': ' 7%\n'},
           {' Polling firm/Link': ' ResearchView\n', ' Fieldwork date': ' 17.04.04–17.04.06\n',
            ' Samplesize': ' 1,012\n', ' Sim Sang-jung': ' 2.2%\n', ' Moon Jae-in': ' 42.4%\n',
            ' Ahn Cheol-soo': ' 35.1%\n', ' Yoo Seong-min': ' 2.5%\n', ' Hong Jun-pyo': ' 10.3%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.04.05\n', ' Samplesize': ' 1,008\n',
            ' Sim Sang-jung': ' 2.5%\n', ' Moon Jae-in': ' 41.3%\n', ' Ahn Cheol-soo': ' 34.5%\n',
            ' Yoo Seong-min': ' 3.0%\n', ' Hong Jun-pyo': ' 9.2%\n'},
           {' Polling firm/Link': ' Surveymob\n', ' Fieldwork date': ' 17.04.04–17.04.05\n', ' Samplesize': ' 1,048\n',
            ' Sim Sang-jung': ' 2.74%\n', ' Moon Jae-in': ' 34.83%\n', ' Ahn Cheol-soo': ' 28.91%\n',
            ' Yoo Seong-min': ' 6.95%\n', ' Hong Jun-pyo': ' 8.09%\n'},
           {' Polling firm/Link': ' JoongAng Ilbo\n', ' Fieldwork date': ' 17.04.04–17.04.05\n',
            ' Samplesize': ' 1,500\n', ' Sim Sang-jung': ' 2.1%\n', ' Moon Jae-in': ' 38.4%\n',
            ' Ahn Cheol-soo': ' 34.9%\n', ' Yoo Seong-min': ' 2.7%\n', ' Hong Jun-pyo': ' 9.6%\n'},
           {' Polling firm/Link': ' EMBRAIN\n', ' Fieldwork date': ' 17.04.04\n', ' Samplesize': ' 1,042\n',
            ' Sim Sang-jung': ' 3.5%\n', ' Moon Jae-in': ' 38.2%\n', ' Ahn Cheol-soo': ' 33.2%\n',
            ' Yoo Seong-min': ' 2.7%\n', ' Hong Jun-pyo': ' 10.3%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.04.04\n', ' Samplesize': ' 1,000\n',
            ' Sim Sang-jung': ' 3.7%\n', ' Moon Jae-in': ' 39.1%\n', ' Ahn Cheol-soo': ' 31.8%\n',
            ' Yoo Seong-min': ' 3.8%\n', ' Hong Jun-pyo': ' 8.6%\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.04.03–17.04.04\n', ' Samplesize': ' 1,708\n',
            ' Sim Sang-jung': ' 3.8%\n', ' Moon Jae-in': ' 40.8%\n', ' Ahn Cheol-soo': ' 30.9%\n',
            ' Yoo Seong-min': ' 2.8%\n', ' Hong Jun-pyo': ' 12.6%\n'}], [
           {' Polling firm/Link': '\n', ' Fieldwork date': '\n', ' Samplesize': '\n', ' Sim Sang-jung': '\n',
            ' Lee Jae-myung': '\n', ' Moon Jae-in': '\n', ' Ahn Hee-jung': '\n', ' Ahn Cheol-soo': '\n',
            ' Sohn Hak-kyu': '\n', ' Yoo Seong-min': '\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.03.27- 17.03.29\n', ' Samplesize': ' 1,525\n',
            ' Sim Sang-jung': ' 3.4%\n', ' Lee Jae-myung': ' 9.5%\n', ' Moon Jae-in': '35.2%\n',
            ' Ahn Hee-jung': ' 12.0%\n', ' Ahn Cheol-soo': ' 17.4%\n', ' Sohn Hak-kyu': ' 2.4%\n',
            ' Yoo Seong-min': ' 2.6%\n', ' Nam Kyung-pil': ' –\n', ' Hwang Kyo-ahn': ' –\n',
            ' Hong Jun-pyo': ' 7.7%\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.03.27- 17.03.28\n', ' Samplesize': ' 1,080\n',
            ' Sim Sang-jung': ' 2.6%\n', ' Lee Jae-myung': ' 11.2%\n', ' Moon Jae-in': '33.0%\n',
            ' Ahn Hee-jung': ' 12.6%\n', ' Ahn Cheol-soo': ' 16.6%\n', ' Sohn Hak-kyu': ' 0.6%\n',
            ' Yoo Seong-min': ' 1.4%\n', ' Nam Kyung-pil': ' 0.7%\n', ' Hwang Kyo-ahn': ' –\n',
            ' Hong Jun-pyo': ' 7.8%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.03.20- 17.03.24\n', ' Samplesize': ' 2,553\n',
            ' Sim Sang-jung': ' 2.9%\n', ' Lee Jae-myung': ' 10.2%\n', ' Moon Jae-in': '34.4%\n',
            ' Ahn Hee-jung': ' 17.1%\n', ' Ahn Cheol-soo': ' 12.6%\n', ' Sohn Hak-kyu': ' 2.2%\n',
            ' Yoo Seong-min': ' 2.2%\n', ' Nam Kyung-pil': ' 1.0%\n', ' Hwang Kyo-ahn': ' –\n',
            ' Hong Jun-pyo': ' 9.5%\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.03.21- 17.03.23\n',
            ' Samplesize': ' 1,007\n', ' Sim Sang-jung': ' 2%\n', ' Lee Jae-myung': ' 8%\n', ' Moon Jae-in': '31%\n',
            ' Ahn Hee-jung': ' 17%\n', ' Ahn Cheol-soo': ' 10%\n', ' Sohn Hak-kyu': ' 1%\n', ' Yoo Seong-min': ' 1%\n',
            ' Nam Kyung-pil': ' –\n', ' Hwang Kyo-ahn': ' –\n', ' Hong Jun-pyo': ' 6%\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.03.19- 17.03.21\n', ' Samplesize': ' 1,589\n',
            ' Sim Sang-jung': ' 2.0%\n', ' Lee Jae-myung': ' 9.4%\n', ' Moon Jae-in': '33.2%\n',
            ' Ahn Hee-jung': ' 17.5%\n', ' Ahn Cheol-soo': ' 11.2%\n', ' Sohn Hak-kyu': ' 1.2%\n',
            ' Yoo Seong-min': ' 2.4%\n', ' Nam Kyung-pil': ' 0.6%\n', ' Hwang Kyo-ahn': ' –\n',
            ' Hong Jun-pyo': ' 7.7%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.03.15\n', ' Samplesize': ' 1,015\n',
            ' Sim Sang-jung': ' 4.1%\n', ' Lee Jae-myung': ' 10.3%\n', ' Moon Jae-in': '37.1%\n',
            ' Ahn Hee-jung': ' 16.8%\n', ' Ahn Cheol-soo': ' 12.0%\n', ' Sohn Hak-kyu': ' 1.8%\n',
            ' Yoo Seong-min': ' 4.8%\n', ' Nam Kyung-pil': ' 1.8%\n', ' Hwang Kyo-ahn': ' –\n',
            ' Hong Jun-pyo': ' 7.1%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.03.14\n', ' Samplesize': ' 1,000\n',
            ' Sim Sang-jung': ' 1.1%\n', ' Lee Jae-myung': ' 8.9%\n', ' Moon Jae-in': '30.7%\n',
            ' Ahn Hee-jung': ' 13.3%\n', ' Ahn Cheol-soo': ' 8.9%\n', ' Sohn Hak-kyu': ' 0.9%\n',
            ' Yoo Seong-min': ' 1.4%\n', ' Nam Kyung-pil': ' 0.7%\n', ' Hwang Kyo-ahn': ' 9.6%\n',
            ' Hong Jun-pyo': ' 2.2%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.03.10\n', ' Samplesize': ' 1,008\n',
            ' Sim Sang-jung': ' 3.3%\n', ' Lee Jae-myung': ' 9.7%\n', ' Moon Jae-in': '36.0%\n',
            ' Ahn Hee-jung': ' 14.5%\n', ' Ahn Cheol-soo': ' 11.3%\n', ' Sohn Hak-kyu': ' 2.6%\n',
            ' Yoo Seong-min': ' 2.4%\n', ' Nam Kyung-pil': ' 1.0%\n', ' Hwang Kyo-ahn': ' 10.1%\n',
            ' Hong Jun-pyo': ' 2.4%\n'}, {' Polling firm/Link': '\n', ' Fieldwork date': '17.03.10\n',
                                          ' Samplesize': 'The Constitutional Court upholds the impeachment of President Park Geun-hye\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.03.06–17.03.07\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 1.3%\n', ' Lee Jae-myung': ' 8.4%\n',
            ' Moon Jae-in': '30.7%\n', ' Ahn Hee-jung': ' 13.7%\n', ' Ahn Cheol-soo': ' 7.6%\n',
            ' Sohn Hak-kyu': ' 1.2%\n', ' Yoo Seong-min': ' 1.2%\n', ' Nam Kyung-pil': ' 0.6%\n',
            ' Hwang Kyo-ahn': ' 11.1%\n', ' Hong Jun-pyo': ' 1.8%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.02.27–17.03.03\n', ' Samplesize': ' 2,025\n',
            ' Sim Sang-jung': ' 1.7%\n', ' Lee Jae-myung': ' 8.9%\n', ' Moon Jae-in': '36.4%\n',
            ' Ahn Hee-jung': ' 12.6%\n', ' Ahn Cheol-soo': ' 10.8%\n', ' Sohn Hak-kyu': ' 2.9%\n',
            ' Yoo Seong-min': ' 2.8%\n', ' Nam Kyung-pil': ' 1.3%\n', ' Hwang Kyo-ahn': ' 14.9%\n',
            ' Hong Jun-pyo': ' 3.8%\n'}], [
           {' Polling firm/Link': '\n', ' Fieldwork date': '\n', ' Samplesize': '\n', ' Sim Sang-jung': '\n',
            ' Lee Jae-myung': '\n', ' Moon Jae-in': '\n', ' Ahn Hee-jung': '\n', ' Ahn Cheol-soo': '\n',
            ' Sohn Hak-kyu': '\n', ' Yoo Seong-min': '\n', ' Nam Kyung-pil': '\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.02.27–17.02.28\n', ' Samplesize': ' 1,111\n',
            ' Sim Sang-jung': ' 0.9%\n', ' Lee Jae-myung': ' 9.8%\n', ' Moon Jae-in': '37.6%\n',
            ' Ahn Hee-jung': ' 15.5%\n', ' Ahn Cheol-soo': ' 11.1%\n', ' Sohn Hak-kyu': ' 1.1%\n',
            ' Yoo Seong-min': ' 1.8%\n', ' Nam Kyung-pil': ' 1.2%\n', ' Ban Ki-moon': ' –\n',
            ' Hwang Kyo-ahn': ' 12.5%\n', ' Hong Jun-pyo': ' 1.4%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.02.24–17.02.25\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' 1.1%\n', ' Lee Jae-myung': ' 10.1%\n',
            ' Moon Jae-in': '30.9%\n', ' Ahn Hee-jung': ' 15.8%\n', ' Ahn Cheol-soo': ' 7.8%\n',
            ' Sohn Hak-kyu': ' 0.8%\n', ' Yoo Seong-min': ' 1.6%\n', ' Nam Kyung-pil': ' 0.1%\n',
            ' Ban Ki-moon': ' –\n', ' Hwang Kyo-ahn': ' 10.3%\n', ' Hong Jun-pyo': ' 1.6%\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.02.21–17.02.23\n',
            ' Samplesize': ' 1,006\n', ' Sim Sang-jung': ' –\n', ' Lee Jae-myung': ' 8%\n', ' Moon Jae-in': '32%\n',
            ' Ahn Hee-jung': ' 21%\n', ' Ahn Cheol-soo': ' 8%\n', ' Sohn Hak-kyu': ' –\n', ' Yoo Seong-min': ' 2%\n',
            ' Nam Kyung-pil': ' –\n', ' Ban Ki-moon': ' –\n', ' Hwang Kyo-ahn': ' 8%\n', ' Hong Jun-pyo': ' –\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.02.20–17.02.22\n', ' Samplesize': ' 1,508\n',
            ' Sim Sang-jung': ' 1.1%\n', ' Lee Jae-myung': ' 10.1%\n', ' Moon Jae-in': '32.4%\n',
            ' Ahn Hee-jung': ' 19.2%\n', ' Ahn Cheol-soo': ' 10.5%\n', ' Sohn Hak-kyu': ' 1.7%\n',
            ' Yoo Seong-min': ' 3.3%\n', ' Nam Kyung-pil': ' 1.8%\n', ' Ban Ki-moon': ' –\n',
            ' Hwang Kyo-ahn': ' 11.6%\n', ' Hong Jun-pyo': ' 3.3%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.02.13–17.02.15\n', ' Samplesize': ' 1,515\n',
            ' Sim Sang-jung': ' 2.5%\n', ' Lee Jae-myung': ' 7.0%\n', ' Moon Jae-in': '32.7%\n',
            ' Ahn Hee-jung': ' 19.3%\n', ' Ahn Cheol-soo': ' 8.6%\n', ' Sohn Hak-kyu': ' 2.8%\n',
            ' Yoo Seong-min': ' 3.9%\n', ' Nam Kyung-pil': ' 1.3%\n', ' Ban Ki-moon': ' –\n',
            ' Hwang Kyo-ahn': ' 16.5%\n', ' Hong Jun-pyo': ' 1.3%\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.02.06–17.02.08\n', ' Samplesize': ' 1,508\n',
            ' Sim Sang-jung': ' 2.6%\n', ' Lee Jae-myung': ' 8.2%\n', ' Moon Jae-in': '33.2%\n',
            ' Ahn Hee-jung': ' 15.7%\n', ' Ahn Cheol-soo': ' 9.1%\n', ' Sohn Hak-kyu': ' 3.1%\n',
            ' Yoo Seong-min': ' 3.5%\n', ' Nam Kyung-pil': ' 1.6%\n', ' Ban Ki-moon': ' –\n',
            ' Hwang Kyo-ahn': ' 15.9%\n', ' Hong Jun-pyo': ' 1.4%\n'},
           {' Polling firm/Link': ' Hankook Research\n', ' Fieldwork date': ' 17.02.05–17.02.06\n',
            ' Samplesize': ' 2,016\n', ' Sim Sang-jung': ' 0.7%\n', ' Lee Jae-myung': ' 6.3%\n',
            ' Moon Jae-in': '29.8%\n', ' Ahn Hee-jung': ' 14.2%\n', ' Ahn Cheol-soo': ' 6.3%\n',
            ' Sohn Hak-kyu': ' 1.1%\n', ' Yoo Seong-min': ' 3.2%\n', ' Nam Kyung-pil': ' 0.6%\n',
            ' Ban Ki-moon': ' –\n', ' Hwang Kyo-ahn': ' 11.2%\n', ' Hong Jun-pyo': ' –\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.02.01–17.02.02\n',
            ' Samplesize': ' 1,003\n', ' Sim Sang-jung': ' 0.6%\n', ' Lee Jae-myung': ' 7%\n', ' Moon Jae-in': '32%\n',
            ' Ahn Hee-jung': ' 10%\n', ' Ahn Cheol-soo': ' 7%\n', ' Sohn Hak-kyu': ' 0.5%\n', ' Yoo Seong-min': ' 3%\n',
            ' Nam Kyung-pil': ' –\n', ' Ban Ki-moon': ' 8%\n', ' Hwang Kyo-ahn': ' 9%\n', ' Hong Jun-pyo': ' –\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.02.01\n', ' Samplesize': ' 1,009\n',
            ' Sim Sang-jung': ' 1.8%\n', ' Lee Jae-myung': ' 9.9%\n', ' Moon Jae-in': '26.1%\n',
            ' Ahn Hee-jung': ' 11.1%\n', ' Ahn Cheol-soo': ' 9.3%\n', ' Sohn Hak-kyu': ' 2.7%\n',
            ' Yoo Seong-min': ' 4.3%\n', ' Nam Kyung-pil': ' 2%\n', ' Ban Ki-moon': ' –\n',
            ' Hwang Kyo-ahn': ' 12.1%\n', ' Hong Jun-pyo': ' 1.4%\n'},
           {' Polling firm/Link': 'Realmeter\n', ' Fieldwork date': ' 17.01.23–17.01.24\n', ' Samplesize': ' 1,004\n',
            ' Sim Sang-jung': ' 1.0%\n', ' Lee Jae-myung': ' 9.5%\n', ' Moon Jae-in': '32.8%\n',
            ' Ahn Hee-jung': ' 6.4%\n', ' Ahn Cheol-soo': ' 7.9%\n', ' Sohn Hak-kyu': ' 2.0%\n',
            ' Yoo Seong-min': ' 2.4%\n', ' Nam Kyung-pil': ' 0.9%\n', ' Ban Ki-moon': ' 15.4%\n',
            ' Hwang Kyo-ahn': ' 7.4%\n', ' Hong Jun-pyo': ' –\n'},
           {' Polling firm/Link': ' Realmeter\n', ' Fieldwork date': ' 17.01.16–17.01.18\n', ' Samplesize': ' 1,507\n',
            ' Sim Sang-jung': ' 1.9%\n', ' Lee Jae-myung': ' 9%\n', ' Moon Jae-in': '28.1%\n', ' Ahn Hee-jung': ' 4%\n',
            ' Ahn Cheol-soo': ' 7.4%\n', ' Sohn Hak-kyu': ' 1.8%\n', ' Yoo Seong-min': ' 2.2%\n',
            ' Nam Kyung-pil': ' 1.2%\n', ' Ban Ki-moon': ' 21.8%\n', ' Hwang Kyo-ahn': ' 4%\n',
            ' Hong Jun-pyo': ' 0.7%\n'},
           {' Polling firm/Link': 'Hankook Research\n', ' Fieldwork date': ' 17.01.15–17.01.16\n',
            ' Samplesize': ' 1,000\n', ' Sim Sang-jung': ' –\n', ' Lee Jae-myung': ' 9.5%\n', ' Moon Jae-in': '31.4%\n',
            ' Ahn Hee-jung': ' 3.9%\n', ' Ahn Cheol-soo': ' 4.8%\n', ' Sohn Hak-kyu': ' 1.3%\n',
            ' Yoo Seong-min': ' 1.2%\n', ' Nam Kyung-pil': ' 0.3%\n', ' Ban Ki-moon': ' 20%\n',
            ' Hwang Kyo-ahn': ' –\n', ' Hong Jun-pyo': ' –\n'},
           {' Polling firm/Link': ' Gallup Korea\n', ' Fieldwork date': ' 17.01.10–17.01.12\n',
            ' Samplesize': ' 1,007\n', ' Sim Sang-jung': ' –\n', ' Lee Jae-myung': ' 12%\n', ' Moon Jae-in': '31%\n',
            ' Ahn Hee-jung': ' 6%\n', ' Ahn Cheol-soo': ' 7%\n', ' Sohn Hak-kyu': ' 2%\n', ' Yoo Seong-min': ' 3%\n',
            ' Nam Kyung-pil': ' –\n', ' Ban Ki-moon': ' 20%\n', ' Hwang Kyo-ahn': ' 5%\n', ' Hong Jun-pyo': ' –\n'},
           {' Polling firm/Link': ' R&Search\n', ' Fieldwork date': ' 17.01.01–17.01.02\n', ' Samplesize': ' 1,153\n',
            ' Sim Sang-jung': ' –\n', ' Lee Jae-myung': ' 10%\n', ' Moon Jae-in': '32.2%\n', ' Ahn Hee-jung': ' 3.9%\n',
            ' Ahn Cheol-soo': ' 5.9%\n', ' Sohn Hak-kyu': ' 3.1%\n', ' Yoo Seong-min': ' 2.1%\n',
            ' Nam Kyung-pil': ' 0.7%\n', ' Ban Ki-moon': ' 21.3%\n', ' Hwang Kyo-ahn': ' 7.2%\n',
            ' Hong Jun-pyo': ' –\n'}], [
           {' Date': ' 14–15 Nov 2016\n', ' Polling firm': ' Realmeter\n', 'Ban Ki-Moon(Nonpartisan)': ' 31.5%\n',
            ' Moon Jae-in(Minjoo)': ' 32.7%\n', " Ahn Cheol-so(People's)": ' 22.8%\n', ' Kim Moo-sung(Saenuri)': '\n',
            ' Undecided/Refused': ' 13%\n', ' Lead': ' 1.2\n'},
           {' Date': ' 37.6%\n', ' Polling firm': ' 46.2%\n', 'Ban Ki-Moon(Nonpartisan)': '\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 16.2%\n', ' Kim Moo-sung(Saenuri)': ' 8.6\n'},
           {' Date': ' 37.2%\n', ' Polling firm': '\n', 'Ban Ki-Moon(Nonpartisan)': ' 39.9%\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 22.9%\n', ' Kim Moo-sung(Saenuri)': ' 2.7\n'},
           {' Date': ' 19–20 Sep 2016\n', ' Polling firm': ' Realmeter\n', 'Ban Ki-Moon(Nonpartisan)': ' 38.5%\n',
            ' Moon Jae-in(Minjoo)': ' 30.6%\n', " Ahn Cheol-so(People's)": ' 18.0%\n', ' Kim Moo-sung(Saenuri)': '\n',
            ' Undecided/Refused': ' 12.9%\n', ' Lead': ' 7.9\n'},
           {' Date': ' 46.7%\n', ' Polling firm': ' 38.4%\n', 'Ban Ki-Moon(Nonpartisan)': '\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 14.9%\n', ' Kim Moo-sung(Saenuri)': ' 8.3\n'},
           {' Date': ' 46.3%\n', ' Polling firm': '\n', 'Ban Ki-Moon(Nonpartisan)': ' 32.5%\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 21.2%\n', ' Kim Moo-sung(Saenuri)': ' 13.8\n'},
           {' Date': ' 13–14 Jun 2016\n', ' Polling firm': ' Realmeter\n', 'Ban Ki-Moon(Nonpartisan)': ' 36.5%\n',
            ' Moon Jae-in(Minjoo)': ' 34.9%\n', " Ahn Cheol-so(People's)": ' 19.0%\n', ' Kim Moo-sung(Saenuri)': '\n',
            ' Undecided/Refused': ' 9.6%\n', ' Lead': ' 1.6\n'},
           {' Date': ' 44.2%\n', ' Polling firm': ' 44.9%\n', 'Ban Ki-Moon(Nonpartisan)': '\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 10.9%\n', ' Kim Moo-sung(Saenuri)': ' 0.7\n'},
           {' Date': ' 40.9%\n', ' Polling firm': '\n', 'Ban Ki-Moon(Nonpartisan)': ' 33.7%\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 25.4%\n', ' Kim Moo-sung(Saenuri)': ' 7.2\n'},
           {' Date': ' 18–19 Apr 2016\n', ' Polling firm': ' Realmeter\n', 'Ban Ki-Moon(Nonpartisan)': ' 42.3%\n',
            ' Moon Jae-in(Minjoo)': ' 42.8%\n', " Ahn Cheol-so(People's)": '\n', ' Kim Moo-sung(Saenuri)': '\n',
            ' Undecided/Refused': ' 14.9%\n', ' Lead': ' 0.5\n'},
           {' Date': ' 41.0%\n', ' Polling firm': '\n', 'Ban Ki-Moon(Nonpartisan)': ' 32.3%\n',
            ' Moon Jae-in(Minjoo)': '\n', " Ahn Cheol-so(People's)": ' 26.7%\n', ' Kim Moo-sung(Saenuri)': ' 8.7\n'},
           {' Date': ' 14–15 Mar 2016\n', ' Polling firm': ' Realmeter\n', 'Ban Ki-Moon(Nonpartisan)': '\n',
            ' Moon Jae-in(Minjoo)': ' 44.0%\n', " Ahn Cheol-so(People's)": '\n', ' Kim Moo-sung(Saenuri)': ' 45.0%\n',
            ' Undecided/Refused': ' 11.0%\n', ' Lead': ' 1.0\n'},
           {' Date': '\n', ' Polling firm': '\n', 'Ban Ki-Moon(Nonpartisan)': ' 37.2%\n',
            ' Moon Jae-in(Minjoo)': ' 44.2%\n', " Ahn Cheol-so(People's)": ' 18.6%\n',
            ' Kim Moo-sung(Saenuri)': ' 7.0\n'},
           {' Date': ' 17–19 Feb 2016\n', ' Polling firm': ' Realmeter\n', 'Ban Ki-Moon(Nonpartisan)': '\n',
            ' Moon Jae-in(Minjoo)': ' 44.3%\n', " Ahn Cheol-so(People's)": '\n', ' Kim Moo-sung(Saenuri)': ' 45.0%\n',
            ' Undecided/Refused': ' 10.7%\n', ' Lead': ' 0.7\n'},
           {' Date': '\n', ' Polling firm': '\n', 'Ban Ki-Moon(Nonpartisan)': ' 37.7%\n',
            ' Moon Jae-in(Minjoo)': ' 43.8%\n', " Ahn Cheol-so(People's)": ' 18.5%\n',
            ' Kim Moo-sung(Saenuri)': ' 6.1\n'}]]

